name: kubectl set image
description: Set image for a resource, see https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-image-em-

inputs:
  context:
    description: either secrets.STAGING_CONTEXT or secrets.PRODUCTION_CONTEXT
    required: true
  type-name:
    description: type name, e.g. deployment/web
    required: true
  container-name:
    description: container name, e.g. web
    required: true
  container-image:
    description: container image, e.g. alpine:3.15.0
    required: true

runs:
  using: composite
  steps:
      -
        name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version
        env:
          KUBECTL_VERSION: 1.20.1
        shell: bash
      -
        # run: kubectl --context ${{ github.event.inputs.context }} set image ${{ github.event.inputs.type-name }} ${{ github.event.inputs.container-name }}=${{ github.event.inputs.container-image }}
        shell: bash
        run: echo ${{ inputs.context }} ${{ inputs.type-name }} ${{ inputs.container-name }}=${{ inputs.container-image }}
