name: kubectl set image
description: Set image for a resource, see https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-image-em-

inputs:
  context:
    description: either secrets.STAGING_CONTEXT or secrets.PRODUCTION_CONTEXT
    required: true
  namespace:
    description: kubernetes namespace to run in
    required: true
  type-name:
    description: type name, e.g. deployment/web
    required: true
  container-name:
    description: container name, e.g. web
    required: true
  container-image:
    description: container image, e.g. alpine:3.15.0
    required: true

runs:
  using: composite
  steps:
      -
        name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl --context ${{ inputs.context }} version
        env:
          KUBECTL_VERSION: v1.20.11
        shell: bash
      -
        shell: bash
        run: kubectl --context ${{ inputs.context }} -n ${{ inputs.namespace }} set image ${{ inputs.type-name }} ${{ inputs.container-name }}=${{ inputs.container-image }}
