name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
#    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
#      run: docker build -t $IMAGE_NAME:$(date +%m%d%Y-%H%M) -t $IMAGE_NAME:latest .
      run: docker build -t $IMAGE_NAME:${{ github.run_id }} -t $IMAGE_NAME:latest .
      env:
        IMAGE_NAME: g3mcbr/docker_web

    - name: Show images
      run: docker images

    - name: Log into Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Push tagged image to Docker Hub
      run: docker push -a g3mcbr/docker_web

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Update kubernetes deployment image
      run: kubectl -n docker-web set image deployment/docker-web docker-web=g3mcbr/docker_web:${{ github.run_id }}
