name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
#    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
#      run: docker build -t $IMAGE_NAME:$(date +%m%d%Y-%H%M) -t $IMAGE_NAME:latest .
      run: docker build -t $IMAGE_NAME:${{ github.run_id }} -t $IMAGE_NAME:latest .
      env:
        IMAGE_NAME: g3mcbr/docker_web

    - name: Show images
      run: docker images

    - name: Log into Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Push tagged image to Docker Hub
      run: docker push -a g3mcbr/docker_web

  deploy:
    # runs-on: self-hosted
    # needs: build
    #
    # steps:
    # - uses: actions/checkout@v2
    #
    # - name: Update kubernetes deployment image
    #   uses: ./.github/actions/kubectl-set-image
    #   with:
    #     context: ${{ secrets.PROD_KUBE_CONTEXT }}
    #     namespace: ${{ secrets.PROD_NS }}
    #     type-name: deployment/${{ secrets.PROD_DEPLOYMENT }}
    #     container-name: ${{ secrets.PROD_CONTAINER }}
    #     container-image: ${{ secrets.PROD_IMAGE }}:${{ github.run_id }}

    runs-on: self-hosted
    needs: Build

    steps:
    # - uses: azure/setup-kubectl@v2.0
    #   with:
    #     version: 'v1.20.12'
    #   id: install
    #
    # - uses: azure/k8s-set-context@v2
    #   with:
    #     method: kubeconfig
    #     context: docker-web-sa

    - uses: Azure/k8s-deploy@v1.4
      with:
      namespace: '${{ secrets.PROD_NS }}'
      manifests: |
          deployment.yaml
      # images: 'contoso.azurecr.io/myapp:${{ event.run_id }}'
      images: '${{ secrets.PROD_IMAGE }}:${{ github.run_id }}'
      kubectl-version: 'v1.20.12'

    - name: Test command
      run: kubectl --context docker-web-sa version
