name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
#    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
#      run: docker build -t $IMAGE_NAME:$(date +%m%d%Y-%H%M) -t $IMAGE_NAME:latest .
      run: docker build -t $IMAGE_NAME:${{ github.run_id }} -t $IMAGE_NAME:latest .
      env:
        IMAGE_NAME: g3mcbr/docker_web

    - name: Show images
      run: docker images

    - name: Log into Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Push tagged image to Docker Hub
      run: docker push -a g3mcbr/docker_web

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Set kubectl context if master
      if: github.ref == 'refs/heads/master'
      run: |
        echo "KUBE_CONTEXT=${{ secrets.PROD_KUBE_CONTEXT }}" >> "$GITHUB_ENV"
        echo "KUBE_NS=${{ secrets.PROD_NS }} >> "$GITHUB_ENV"
        echo "KUBE_DEPLOYMENT=${{ secrets.PROD_DEPLOYMENT }} >> "$GITHUB_ENV"
        echo "KUBE_CONTAINER=${{ secrets.PROD_CONTAINER }} >> "$GITHUB_ENV"
        echo "KUBE_IMAGE=${{ secrets.PROD_IMAGE }} >> "$GITHUB_ENV"

    - name: Set kubectl context if stage
      if: github.ref == 'refs/heads/stage'
      run: |
        echo "KUBE_CONTEXT=${{ secrets.STAGE_KUBE_CONTEXT }}" >> "$GITHUB_ENV"
        echo "KUBE_NS=${{ secrets.STAGE_NS }} >> "$GITHUB_ENV"
        echo "KUBE_DEPLOYMENT=${{ secrets.STAGE_DEPLOYMENT }} >> "$GITHUB_ENV"
        echo "KUBE_CONTAINER=${{ secrets.STAGE_CONTAINER }} >> "$GITHUB_ENV"
        echo "KUBE_IMAGE=${{ secrets.STAGE_IMAGE }} >> "$GITHUB_ENV"

    - name: Install kubectl
      run: |
        curl -LO https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    - name: set context
      run: kubectl config use-context $KUBE_CONTEXT
 
    - name: Update kubernetes deployment image
      run: kubectl -n $KUBE_NS set image deployment/$KUBE_DEPLOYMENT $KUBE_CONTAINER=$KUBE_IMAGE:${{ github.run_id }}
#      run: kubectl -n docker-web set image deployment/docker-web docker-web=g3mcbr/docker_web:${{ github.run_id }}
#      run: kubectl -n stage set image deployment/nginx-deployment nginx=nginx:1.20
